### PR TITLE
Promote develop to main

### LINKED ISSUE #421: WORKFLOW.md drift: stale configure.sh subcommands and NUGET_USERNAME secret store
Surfaced by Copilot review on #420 and verified against the tree and live repo state. Both are documentation drift in `WORKFLOW.md`, pre-existing on `develop` (carried in with #417), not regressions from #420.

## 1. `configure.sh check` / `apply` no longer exist

`WORKFLOW.md` references subcommands the script does not implement:

- line 589: "Run `repo-config/configure.sh check` (section 6)"
- line 659: "`repo-config/configure.sh check` reads the live rulesets ... that command **is** the 5D audit"
- line 660: "`repo-config/configure.sh apply` configures a fresh repo"

The current interface is `repo-config/configure.sh [owner/repo] [release|operational]`. Because arg 1 is the repo, invoking `configure.sh check` would be parsed as **repo name `check`**, not a subcommand -- so the documented command silently does the wrong thing rather than erroring helpfully.

The audit flow also moved to `AUDIT.md`, which is now the read-only drift-reporting authority. `WORKFLOW.md` still describes `configure.sh check` as "the 5D audit".

**Fix:** update the three `WORKFLOW.md` references to point at the `AUDIT.md` flow for auditing and the current `configure.sh` argument form for applying.

## 2. `NUGET_USERNAME` secret store is documented inconsistently

`WORKFLOW.md` line 621-622 says `NUGET_USERNAME` is **Actions store**, and pointedly contrasts it with the App pair, which it says is "required in **both** the Actions and Dependabot secret stores".

But `spec/secrets.json` declares `"stores": ["actions", "dependabot"]` for the `nuget-oidc` mechanism, and `AUDIT.md` line 42 states the name "live[s] in both the Actions and Dependabot stores" and iterates both stores in its check snippet.

**Note the consequence Copilot predicted does not occur.** The review claimed the audit would report a false defect; live state shows the secret is present in *both* stores:

```
actions:    CODECOV_TOKEN CODEGEN_APP_CLIENT_ID CODEGEN_APP_PRIVATE_KEY NUGET_USERNAME
dependabot: CODECOV_TOKEN CODEGEN_APP_CLIENT_ID CODEGEN_APP_PRIVATE_KEY NUGET_USERNAME
```

So the audit passes today. The defect is purely that the three documents disagree, which will mislead the next person reconciling them.

**Fix:** decide which is authoritative and align. `spec/secrets.json` and `AUDIT.md` match live state, so the likely correction is `WORKFLOW.md` line 621. Worth confirming against the fleet hub's canonical spec, and worth asking whether Dependabot genuinely needs `NUGET_USERNAME` -- publishing runs on `push` to `main` with the Actions store, so the Dependabot copy may be unnecessary rather than required.

## Fleet note

`WORKFLOW.md` and `repo-config/` are carried from ProjectTemplate, so both items may need fixing upstream rather than only here.

### PR DESCRIPTION
**Pull request by ptr727**
Promotion of the `WORKFLOW.md` drift fix to `main`.

## Contents

| PR | Change |
| --- | --- |
| #422 | Correct the 5D audit references (`configure.sh check`/`apply` -> AUDIT.md) and the `NUGET_USERNAME` secret store |

Closes #421

## What was fixed

1. **`configure.sh check` / `apply` do not exist.** The script's interface is `[owner/repo] [release|operational]`, so `check` parsed as a *repository name* -- acting on the wrong target rather than erroring. Auditing moved to `AUDIT.md` as a read-only procedure; `configure.sh` only applies.
2. **`NUGET_USERNAME` store.** `WORKFLOW.md` claimed Actions-only while `spec/secrets.json` and `AUDIT.md` claimed both. Resolved in favor of both, matching the fleet hub's canonical `nuget-oidc` mechanism and live repository state (the name is present in both stores).

Two further accuracy fixes came out of review: the NuGet.org trusted-publishing policy is now correctly described as sitting *outside* AUDIT.md's drift report, and the `configure.sh` model argument note now covers the no-registry fallback to `release`.

## Release impact: no auto-publish

Docs-only. No shipped input (`Utilities/**`, `version.json`, `Directory.Build.props`, `Directory.Packages.props`) is touched, so this will correctly not trigger a stable release. NuGet stays at 4.0.18, whose library content is already identical to `main`.

### CODE REVIEW

File: WORKFLOW.md [hunk 1]
```diff
@@ -586,14 +586,14 @@ determined by NBGV from the checkout state in section 3.*
...
 ### 5D. Configuration audit
 
-Run [`repo-config/configure.sh check`](./repo-config/) (section 6). It confirms the listed secrets exist,
+Follow the read-only audit in [`AUDIT.md`](./AUDIT.md) (section 6). It confirms the listed secrets exist,
 the `main`/`develop` rulesets enforce the required merge method + status check + signed commits +
-strict-off, and the repository settings (auto-merge, allowed merge methods) are in place, exiting non-zero
-on any drift. A missing or incorrect configuration item is a defect (D10). Secret *values* cannot be read
+strict-off, and the repository settings (auto-merge, allowed merge methods) are in place, reporting any
+drift. A missing or incorrect configuration item is a defect (D10). Secret *values* cannot be read
 back, so the audit asserts the names exist (failing if it cannot query them); the GitHub App installation is a
```
[the remark this answers is not in the document]
Comment (ptr727) [reply WORKFLOW.md]: Confirmed and fixed in #424 (ad45bb4), now merged into `develop` so this promotion picks it up.

You are right that AUDIT.md defines no non-zero exit contract - its secrets check is `echo`-based (`... || echo "$store/$s: MISSING (defect)"`). The "asserts / failing" wording was inherited from when `configure.sh check` performed the audit and exited non-zero; #422 moved the audit but left these clauses describing the old behavior. Both now say the audit checks the names and reports a missing name or failed query as a defect.

File: WORKFLOW.md [hunk 2]
```diff
@@ -655,8 +657,12 @@ first successful publish locks it to the repo and owner IDs.
...
-to match. Secret values cannot be read back, so the audit asserts the names exist (failing if they cannot be queried);
+and repository settings as JSON, applied by an idempotent `gh api` script and audited read-only per
+[`AUDIT.md`](./AUDIT.md).
+[`AUDIT.md`](./AUDIT.md) diffs the live rulesets, settings, and secret names against the committed
+baseline and reports drift without changing anything; that procedure **is** the 5D audit.
+`repo-config/configure.sh [owner/repo] [release|operational]` applies the baseline to a repo (idempotent;
+both arguments optional - the repo defaults to the current one, and the model to the registry lookup,
+falling back to `release` with a warning when no registry is present).
+Secret values cannot be read back, so the audit asserts the names exist (failing if they cannot be queried);
 the App installation is a best-effort check.
```
[the remark this answers is not in the document]
Comment (ptr727) [reply WORKFLOW.md]: Same fix in #424 (ad45bb4) - this sentence now reads "the audit checks that the names exist, reporting a missing name or a failed query as a defect", matching AUDIT.md's read-only reporting behavior.

File: WORKFLOW.md [hunk 3]
```diff
@@ -586,14 +586,15 @@ determined by NBGV from the checkout state in section 3.*
...
-Run [`repo-config/configure.sh check`](./repo-config/) (section 6). It confirms the listed secrets exist,
+Follow the read-only audit in [`AUDIT.md`](./AUDIT.md) (section 6). It confirms the listed secrets exist,
 the `main`/`develop` rulesets enforce the required merge method + status check + signed commits +
-strict-off, and the repository settings (auto-merge, allowed merge methods) are in place, exiting non-zero
-on any drift. A missing or incorrect configuration item is a defect (D10). Secret *values* cannot be read
-back, so the audit asserts the names exist (failing if it cannot query them); the GitHub App installation is a
-best-effort check (a precise check needs app-level auth, so it notes rather than fails). The NuGet.org trusted-publishing
-policy (D4.7) lives outside GitHub and cannot be checked by `gh api`; the script flags it as a manual
-verification item.
+strict-off, and the repository settings (auto-merge, allowed merge methods) are in place, reporting any
```
[the remark this answers is not in the document]
Comment (ptr727) [reply WORKFLOW.md:591]: Fair point, but declining **on this PR** as out of scope - tracked for a separate pass rather than dropped.

You are right about the inconsistency: `strict-off` appears exactly once (line 591), while section 6 spells the same setting out as `"require branches up to date before merging" is **off**` and `"up to date" is **off**`.

Two reasons to leave it here:

1. **Pre-existing, unrelated to this change.** `git log -S` puts `strict-off` at fcd4f92 (#349), well before this work. This promotion closes #421, which is specifically the `configure.sh` subcommand drift and the `NUGET_USERNAME` store.
2. **Third round of adjacent wording nits on the same paragraphs.** AGENTS.md "Triaging Review Comments" flags exactly this pattern - repeated rounds on one style category without convergence - as the signal to stop and batch rather than keep bouncing the same file. Each round here costs a full develop PR plus a promotion re-review.

Resolving so the merge gate reflects a triaged finding rather than an ignored one. Raising a WORKFLOW.md terminology-consistency pass with the maintainer as separate work.
